<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2007/12/01 10:35:14
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
